import { Router } from "express";

import dashboardRoutes from "./dashboard.routes.js";
import productRoutes from "./product.routes.js";
import inventoryRoutes from "./inventory.routes.js";
import orderRoutes from "./order.routes.js";
import customerRoutes from "./customer.routes.js";
import reviewRoutes from "./review.routes.js";
import couponRoutes from "./coupon.routes.js";
import notificationRoutes from "./notification.routes.js";
import analyticsRoutes from "./analytics.routes.js";
import profileRoutes from "./profile.routes.js";
import financeRoutes from "./finance.routes.js";
import shipmentRoutes from "./shipment.routes.js";
import invoiceRoutes from "./invoice.routes.js";
import supportRoutes from "./support.routes.js";
import loyaltyRoutes from "./loyalty.routes.js";
import referralRoutes from "./referral.routes.js";
import walletRoutes from "./wallet.routes.js";
import marketingRoutes from "./marketing.routes.js";
import uploadRoutes from "./upload.routes.js";
import exportRoutes from "./export.routes.js";
import activityRoutes from "./activity.routes.js";
import audienceSegmentRoutes from "./audienceSegment.routes.js";
import warehouseRoutes from "./warehouse.routes.js";
import brandRoutes from "./brand.routes.js";
import categoryRoutes from "./category.routes.js";

const router = Router();
router.use("/warehouses", warehouseRoutes);
router.use("/brands", brandRoutes);
router.use("/categories", categoryRoutes);
router.use("/activities", activityRoutes);
router.use("/audience-segments", audienceSegmentRoutes);
router.use("/exports", exportRoutes);
router.use("/uploads", uploadRoutes);
router.use("/marketing", marketingRoutes);
router.use("/loyalty", loyaltyRoutes);
router.use("/referrals", referralRoutes);
router.use("/wallets", walletRoutes);
router.use("/support", supportRoutes);
router.use("/invoices", invoiceRoutes);
router.use("/shipments", shipmentRoutes);
router.use("/finance", financeRoutes);
router.use("/analytics", analyticsRoutes);
router.use("/profile", profileRoutes);
router.use("/notifications", notificationRoutes);
router.use("/coupons", couponRoutes);
router.use("/dashboard", dashboardRoutes);
router.use("/products", productRoutes);
router.use("/inventory", inventoryRoutes);
router.use("/orders", orderRoutes);
router.use("/customers", customerRoutes);
router.use("/reviews", reviewRoutes);
export default router;
